### ISSUE TITLE
Support Addressable: add, getByName, Update and delete by id

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-cli#151]
# 🚀 Feature Request
Add missing Addressable functionality: 

- Creates a new Addressable and returns the ID of the new item if successful.
- Get Addressable for  specified ID
- Get Addressable for the specified name
- Update the Addressable data
-  Delete  Addressable by specified ID

**Comment by jpwhitemn** [comment]
@difince @mkbhanda - I would make this enhancement a low priority given that Addressable is being removed with Hanoi.

**Comment by difince** [comment]
Because Addressable are going to be remove in Hanoi, I am deleting this issue directly
