### ISSUE TITLE
Roadmap 2020 and beyond

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-cli#199]
# 🚀 Feature Request

### Description
This is a running list to collect CLI features requests from the EdgeX community that would make it a compelling component. Prioritising and finding folks who can work on them is a separate issue.
If you have never played with the CLI, here are some links.
https://www.youtube.com/watch?v=Cclr4VdkzXY
https://blogs.vmware.com/opensource/2020/02/11/cli-edgex-foundry/
### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by difince** [comment]
@jpwhitemn for visibility. 
This Feature Request running list could be propagated during the SMA/TSC meetings if we got talk/conversations about CLI

**Comment by difince** [comment]
- Add registry support

- Make CLI  support both Secure and Insecure EdgeXFoundry instances ([issue](https://github.com/edgexfoundry-holding/edgex-cli/issues/207))

- Show EdgeX microservice specific metrics 

- Show EdgeX microservice configuration

- Show/Manage CLI configuration  

- App Services and Device Services

- Integrate CLI within SNAP

**Comment by tonyespy** [comment]
Since we have a roadmap document for the client, does it make sense to keep this issue open?
