### ISSUE TITLE
url not available via go-mod-core-contracts client interface

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-cli#219]
# 🐞 Bug Report
When go-mod-contracts interface clients are used to create the requests - the CLI as i client does not have the knowledge what is the URL used to construct the request. 
That is the reason why flag --url to have no effect  with commands that use go-mod-core-contracts clients on the background.
 
The url is printed only when [request.go](https://github.com/edgexfoundry-holding/edgex-cli/blob/master/pkg/request.go) functions are used. 

### Affected Command
device
event
interval
profile
watcher

Are we going to embrace more go-mod-core-contracts interface clients ? 
And if yes, how we could know what is the url used when the request is constructed, so we could print it ?

**Comment by difince** [comment]
@mkbhanda

**Comment by siggiskulason** [comment]
Version 2.0 of the client only uses go-mod-core-contracts and does not call the REST API URLs directly - so it will not support printing the URLs.
