### ISSUE TITLE
--verbose: post requests -When go-mod-core-contracts are used to construct the requests the request body is not printed out

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-cli#220]
# 🐞 Bug Report
When go-mod-contracts interface clients are used to create POST requests - we miss to print the constructed body as part of --verbose flag 

Need to figure out a common way to do it

### Affected Command
device add 
event add
profile add

**Comment by difince** [comment]
@mkbhanda for visibility

**Comment by tonyespy** [comment]
@difince when you say "constructed body" do you mean the request body sent to the service? If so, why would you want to print that when -v is specified? My expectation for "-v" is that it should only cause the raw response body to be printed.

**Comment by difince** [comment]
@tonyespy Yes, I meant "request body" 

In my understanding the verbose flag should help the cli users to understand what are the exact requests - including printing out the request body, the response and the used URL

**Comment by tonyespy** [comment]
@difince As part of my snap packaging testing, I ran all of the latest commands (list only), and noticed that `-v` only causes the response body to be printed which is the behavior I expected, whereas your last comment on Aug 6 states that `-v` should cause both the request body and response body to be printed. I think this is wrong as it will break jq (i.e. you won't be able to pipe the output of the command to `jq`).

This issue also has a reference to PR [#292](https://github.com/edgexfoundry/edgex-cli/pull/292) which updated the help text for `-v` to say that both are printed, however all of the commands currently only print the response body.

IMHOP the goal of the client is to provide a convenient developer tool tool not educate users on how the underlying API works.

If you're planning on changing the actual behavior of all the commands to match the updated help text, then please let me know how I'm supposed to use the commands if I only want to see the response body.

**Comment by siggiskulason** [comment]
The -v behaviour changed in V2, so I'm closing this issue.
