### ISSUE TITLE
Windows support - Makefile needs to be OS aware for paths

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-cli#223]
# 🐞 Bug Report

### Affected Command
Directory path needs to be OS aware for locating the config file for the install and clean targets.
Useful resources:
1) https://stackoverflow.com/questions/4058840/makefile-that-distincts-between-windows-and-unix-like-systems
2) https://stackoverflow.com/questions/714100/os-detecting-makefile
Could introduce a config-file variable that is defined differently based on OS

This is more than adequate for our purposes:
ifeq ($(OS),Windows_NT)     # is Windows_NT on XP, 2000, 7, Vista, 10...
    detected_OS := Windows
else
    detected_OS := $(shell uname)  # same as "uname -s"
endif

Alternately

ifeq '$(findstring ;,$(PATH))' ';'
    detected_OS := Windows
else
    detected_OS := $(shell uname 2>/dev/null || echo Unknown)
    detected_OS := $(patsubst CYGWIN%,Cygwin,$(detected_OS))
    detected_OS := $(patsubst MSYS%,MSYS,$(detected_OS))
    detected_OS := $(patsubst MINGW%,MSYS,$(detected_OS))
endif

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
Not relevant after https://github.com/edgexfoundry/edgex-cli/pull/284
