### ISSUE TITLE
Sometimes the -v/--verbose flag causes the HTTP method and URL to be output

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-cli#244]
Version: 0.0.1

Sometimes when the **-v/--verbose** flag is specified, it also causes the HTTP method and URL to be printed.

If the output of a command that does this is then piped to jq, it causes a parse error.

Ex.

```
$ edgex-cli addressable list -v | jq .
"parse error: Invalid numeric literal at line 1, column 2"
```

Affected commands:
 * addressable list
 * command list
 * deviceservice list
 * reading list

I didn't check interval list, notification list, or subscription list as I didn't have support-notifications configured/enabled.

**Comment by difince** [comment]
as I commented out https://github.com/edgexfoundry/edgex-cli/issues/220#issuecomment-669861868 
In my undestanding -v shoudl provide all request body, response  and url ..
So lets first specify what exactly we want to be printed when -v is provided  ... 

In addition, we could implement pretty print by yourself by adding global flag --pretty
Future enhancement could be even enabling pretty print by providing custom Go template ... ?

**Comment by tonyespy** [comment]
@difince if one of our goals is to replace developer written **curl** scripts, then edgex-cli needs to be provide similar behavior. The reason including the URL in the verbose output is a problem is that the output of the command is no longer raw JSON, therefore it can't be properly parsed by the **jq** command. Almost all of my existing **curl** shell scripts rely on this behavior. If you want to see other "response" objects (eg. HTTP status), you need to explicitly enable them.

**Note** - the current help output for verbose says:

>   -v, --verbose              Print entire HTTP response.

It doesn't state that it also generates the request URL. Also why would you want -v to output the "request body" too?

**Comment by nkstanchev** [comment]
In my opinion, when it comes to semantics the -v/--verbose flag should provide additional information regarding the request and response (url, req body etc.).

Having said that, it is also true that CLI cmds are supposed to replace raw curl cmds and they should fulfil the need for raw json output as well as other scripting needs.

To solve this, I propose an additional optional flag -o/--output which specifies the type of output and has the following behaviour:
- The flag should be exclusive with the --verbose flag or have precedence over it
- If the flag is not provided, the output is based on the output template and --verbose is taken into consideration (basically what we have now)

This would decouple verbosity with output format and provide an extensible way to add support for other formats (yaml, toml) if needed in the future. This approach is similar to the one in kubectl.

`kubectl get pods -o json`

**Comment by tonyespy** [comment]
@nkstanchev thanks for the response. What I still don't like about the existing verbose behavior is that we're mixing simple strings (e.g. the URL) with JSON (the response body). Does kubectl ever produce mixed output like this?

That said, as long as we make all the commands consistent in behavior (i.e. right now some of the commands only output the JSON response when **--verbose** is specified, and some output the JSON response and the URL). If the latter is what we really think we want, then I guess I'm OK with it, as long as we implement your suggested **-o** option.

Also if we're going to implement this, is there really a need for the separate **-u** option to request that the endpoint URL is also output?

**Comment by jpwhitemn** [comment]
Per the Core Working Group today, it was decided that for the Hanoi release, we will support -v that provides only JSON data (so that it can be piped to jq or other tool).  Use -u if you need the URL (however go-mod-core-contracts needs to be able to provide the URL and that issue is being worked).  For this release, there will be no -o option.  We can revisit alternative output for future releases.
