### ISSUE TITLE
Upgrade to Go 1.15.1

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-cli#268]
# 🚀 Feature Request

### Description
Upgrade all services to use Go 1.15.1.

### Describe the solution you'd like
Update the Dockerfile, Dockerfile.build, go.mot to use golang:1.15-alpine base image

### Describe alternatives you've considered
n/a

**Comment by difince** [comment]
Fixed by https://github.com/edgexfoundry/edgex-cli/pull/282
