### ISSUE TITLE
Add Attribution.txt file in preparation for building deployment bundle

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-cli#287]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mkbhanda** [comment]
app-service-configurable. includes in its bin directory and runs as part of its tests 2 scripts
test-attribution-txt.sh	test-go-mod-tidy.sh
to ensure that attributions are accurate. 
Need to add

**Comment by difince** [comment]
Fix by PR https://github.com/edgexfoundry/edgex-cli/pull/291
