### ISSUE TITLE
Make clean deletes the test related scripts in the bin directory

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-cli#313]
# 🐞 Bug Report

### Affected Command

 The issue is located in: 

### Is this a regression?
Yes. This behavior observed after the introduction of " rm -rf $(ARTIFACT_ROOT)" in the clean target.
Perhaps adequate to " rm -rf $(ARTIFACT_ROOT)/$(BINARY)" ?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
Fixed by https://github.com/edgexfoundry/edgex-cli/pull/322
