### ISSUE TITLE
Many commands don't properly implement -u support

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-cli#334]
Many of the current edgex-cli commands don't properly support the `-u` command-line option, which tells the command to output the URL of the API endpoint used by the command before displaying the normal output.

The affected commands are:

- interval
- device
- event
- profile
- watcher

**Note** - I only tested the "list" form of each command, so the behavior of the other sub-commands still probably needs to be re-tested.

**Version**: v1.0.0-dev.28

**Comment by difince** [comment]
This issue duplicates https://github.com/edgexfoundry/edgex-cli/issues/219
