### ISSUE TITLE
Why support a help command and command-line option?

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-cli#338]
The current client supports a command-line option for help (`-h / --help`) and a top-level help command. Are both really needed?

Version: v1.0.0-dev.28

**Comment by difince** [comment]
I am not sure if I understand your point correctly. But IMHO I think that we need `--help` at all levels: at a top-level (edgex-cli --help) and at all specific command levels

**Comment by siggiskulason** [comment]
Both are supported by default by the CLI library (Cobra) and are autogenerated.
