### ISSUE TITLE
Missing Configuration file -> Fails to run any command

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-cli#353]
# 🐞 Bug Report

### Affected Command
All commands

### Is this a regression?
No , the issue always existed

### Description and Minimal Reproduction
The installation process (make install) copies this configuration.toml file and paste it in $HOME/.edgex-cli/ folder.
But we are doing this if we firstly cole the project and instal/build it from source. 
The released executable [tar files](https://github.com/edgexfoundry/edgex-cli/releases/tag/v1.0.0) contain just the edgex-cli executable with License and Attribution.txt  files -> on clean system, this executable fails to run any command because of: 
`Error occurred while parsing /home/difince/.edgex-cli/configuration.toml: open /home/difince/.edgex-cli/configuration.toml: no such file or directory`

## 🔥 Exception or Error
<pre><code>

Error occurred while parsing /home/difince/.edgex-cli/configuration.toml: open /home/difince/.edgex-cli/configuration.toml: no such file or directory

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by mkbhanda** [comment]
It is easy enough to include the configuration.toml file into the tar ball by modifying the Makefile.
We could either put it in a res sub-directory in the tar ball by making a change such as below for each of the architecture targets:

tar -czvf ${ARTIFACT_ROOT}/$(BINARY)-mac-$(VERSION).tar.gz Attribution.txt LICENSE res/configuration.toml -C ${ARTIFACT_ROOT} $(BINARY)-mac


But there still remains an installation step of copying it over to the $HOME/.edgex-cli directory.
Would need to add that to the README file on how to install or an additional install script to be packaged in the tarball.
Snap version needs edit too.

**Comment by mkbhanda** [comment]
The hash codes mentioned in snap yaml would need to change

In addition need to create the .edgex-cli directory and copy configuration.tml there, basically editing line 72

install -DT "./res/configuration.toml" "$SNAPCRAFT_PART_INSTALL/res/configuration.toml"
