### ISSUE TITLE
Related to issue 353, need to edit snap support.

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-cli#356]
# 🐞 Bug Report

### Affected Command

 The issue is located in: 

Related to https://github.com/edgexfoundry/edgex-cli/issues/353
### Is this a regression?

No, existed

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by tonyespy** [comment]
@mkbhanda the snap already included a wrapper script which automatically copied the configuration file into place. I already provided @difince with a patch to remove this snap code which she's included in her PR, so this issue can be closed.

**Comment by difince** [comment]
issue fix in PR https://github.com/edgexfoundry/edgex-cli/pull/361
