### ISSUE TITLE
could I using edgex-cli to deploy device service

### ISSUE THREAD

**Issue by zhanglu0704** [edgexfoundry/edgex-cli#373]
Could I using edgex-cli to deploy device service like modbus-device-service? And how?

**Comment by tonyespy** [comment]
@zhanglu0704 edgex-cli is a command-line tool which allows you to directly interact with the REST APIs of EdgeX microservices. Think of it as a replacement for developers tools like curl or Postman. As such, you can't really use it to deploy a device service. Please refer to the EdgeX [device service documentation](https://docs.edgexfoundry.org/1.3/microservices/device/Ch-DeviceServices/) for information about how to use device services. If you're just interested in device-modbus, then refer to this [tutorial](https://docs.edgexfoundry.org/1.2/examples/Ch-ExamplesAddingModbusDevice/) for how to get started.

@jpwhitemn can you please close this issue, as I don't have permission to do so.

**Comment by zhanglu0704** [comment]
Thanks for your reply. I got it.
