### ISSUE TITLE
Upgrade CLI to V2 (remove addressable)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-cli#381]
# 🚀 Feature Request

### Description
Upgrade to V2 API - remove addressable command elements

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by siggiskulason** [comment]
Addressable was not included in the V2 implementation of the CLI
