### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry/edgex-cli#75]
# 🚀 Feature Request

### Description
We need documentation to help new users install and use the CLI. This documentation would live in both this repository and in `docs.edgexfoundry.org`.

### Describe the solution you'd like

We can write a `.md` page, which should be compatible with .rst which is used for `docs.edgexfoundry.org`.

**Comment by difince** [comment]
Issue that accomodates a few other separate issues - https://github.com/edgexfoundry/edgex-cli/issues/254, https://github.com/edgexfoundry/edgex-cli/issues/253, https://github.com/edgexfoundry/edgex-cli/issues/208
Closing this issue ...
