### ISSUE TITLE
Implement SMA calls: Start, restart, and stop

### ISSUE THREAD

**Issue by couralex6** [edgexfoundry/edgex-cli#97]
# 🚀 Feature Request

### Description
As long as SMA service is running, we can start, stop, and restart any service. We should have a command for each of these actions and for each individual service or all services at once.

### Describe the solution you'd like

`$ edgex-cli [start | restart | stop] [service (optional)]

### Describe alternatives you've considered
Working with docker directly.

**Comment by couralex6** [comment]
Makes issue #74 obsolete.

**Comment by siggiskulason** [comment]
The SMA has been deprecated in Ireland/Jakarta so version 2 of edgex-cli will not support system management endpoints
